using System.Xml.Linq;

namespace Gmsd.Agents.Execution.ControlPlane.Tools.Standard;

/// <summary>
/// Parses TRX (Test Results XML) files generated by dotnet test into structured data.
/// </summary>
public sealed class TrxResultParser
{
    /// <summary>
    /// Parses a TRX file and extracts test results.
    /// </summary>
    public TrxParseResult ParseTrxFile(string filePath)
    {
        if (!File.Exists(filePath))
        {
            return new TrxParseResult { TotalTests = 0, Passed = 0, Failed = 0, Failures = new List<FailureDetail>() };
        }

        try
        {
            var doc = XDocument.Load(filePath);
            var root = doc.Root;

            if (root == null)
            {
                return new TrxParseResult { TotalTests = 0, Passed = 0, Failed = 0, Failures = new List<FailureDetail>() };
            }

            var ns = root.Name.NamespaceName;
            var xns = string.IsNullOrEmpty(ns) ? XNamespace.None : XNamespace.Get(ns);

            // Extract test results summary
            var resultsElement = root.Element(xns + "ResultSummary");
            var countersElement = resultsElement?.Element(xns + "Counters");

            var totalTests = 0;
            var passed = 0;
            var failed = 0;

            if (countersElement != null)
            {
                totalTests = int.TryParse(countersElement.Attribute("total")?.Value, out var t) ? t : 0;
                passed = int.TryParse(countersElement.Attribute("passed")?.Value, out var p) ? p : 0;
                failed = int.TryParse(countersElement.Attribute("failed")?.Value, out var f) ? f : 0;
            }

            // Extract failure details
            var failures = new List<FailureDetail>();
            var unitTestResultsElement = root.Element(xns + "Results");

            if (unitTestResultsElement != null)
            {
                foreach (var testResult in unitTestResultsElement.Elements(xns + "UnitTestResult"))
                {
                    var outcome = testResult.Attribute("outcome")?.Value;
                    if (outcome == "Failed")
                    {
                        var testName = testResult.Attribute("testName")?.Value ?? "Unknown";
                        var outputElement = testResult.Element(xns + "Output");
                        var errorInfoElement = outputElement?.Element(xns + "ErrorInfo");
                        var message = errorInfoElement?.Element(xns + "Message")?.Value ?? "No error message";
                        var stackTrace = errorInfoElement?.Element(xns + "StackTrace")?.Value ?? "";

                        failures.Add(new FailureDetail
                        {
                            TestName = testName,
                            Message = message,
                            StackTrace = stackTrace
                        });
                    }
                }
            }

            return new TrxParseResult
            {
                TotalTests = totalTests,
                Passed = passed,
                Failed = failed,
                Failures = failures
            };
        }
        catch (Exception ex)
        {
            return new TrxParseResult
            {
                TotalTests = 0,
                Passed = 0,
                Failed = 0,
                Failures = new List<FailureDetail> { new FailureDetail { TestName = "Parser Error", Message = ex.Message } }
            };
        }
    }
}

/// <summary>
/// Represents parsed TRX test results.
/// </summary>
public sealed class TrxParseResult
{
    public int TotalTests { get; set; }
    public int Passed { get; set; }
    public int Failed { get; set; }
    public List<FailureDetail> Failures { get; set; } = new();
}

/// <summary>
/// Represents a single test failure.
/// </summary>
public sealed class FailureDetail
{
    public string TestName { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public string StackTrace { get; set; } = string.Empty;
}
