// <auto-generated />
using Gmsd.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gmsd.Data.Migrations
{
    [DbContext(typeof(GmsdDbContext))]
    [Migration("20260207022348_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Gmsd.Data.Entities.Projects.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = "proj-sample-001",
                            Name = "Sample Web Application"
                        },
                        new
                        {
                            ProjectId = "proj-sample-002",
                            Name = "API Migration Project"
                        },
                        new
                        {
                            ProjectId = "proj-sample-003",
                            Name = "Database Optimization Initiative"
                        });
                });

            modelBuilder.Entity("Gmsd.Data.Entities.Projects.Step", b =>
                {
                    b.Property<string>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StepId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Step");
                });

            modelBuilder.Entity("Gmsd.Data.Entities.Projects.Step", b =>
                {
                    b.HasOne("Gmsd.Data.Entities.Projects.Project", "Project")
                        .WithMany("Steps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gmsd.Data.Entities.Projects.Project", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
