// <auto-generated />
using System;
using nirmata.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nirmata.Data.Migrations
{
    [DbContext(typeof(nirmataDbContext))]
    [Migration("20260324000001_AddChatMessagesTable")]
    partial class AddChatMessagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("nirmata.Data.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("NextCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Timestamp");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = "proj-sample-001",
                            Name = "Sample Web Application"
                        },
                        new
                        {
                            ProjectId = "proj-sample-002",
                            Name = "API Migration Project"
                        },
                        new
                        {
                            ProjectId = "proj-sample-003",
                            Name = "Database Optimization Initiative"
                        });
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Step", b =>
                {
                    b.Property<string>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StepId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Step");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("nirmata.Data.Entities.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Step", b =>
                {
                    b.HasOne("nirmata.Data.Entities.Projects.Project", "Project")
                        .WithMany("Steps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Project", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
