// <auto-generated />
using System;
using nirmata.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nirmata.Data.Migrations
{
    [DbContext(typeof(nirmataDbContext))]
    partial class nirmataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = "proj-sample-001",
                            Name = "Sample Web Application"
                        },
                        new
                        {
                            ProjectId = "proj-sample-002",
                            Name = "API Migration Project"
                        },
                        new
                        {
                            ProjectId = "proj-sample-003",
                            Name = "Database Optimization Initiative"
                        });
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Step", b =>
                {
                    b.Property<string>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StepId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Step");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Workspaces.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Step", b =>
                {
                    b.HasOne("nirmata.Data.Entities.Projects.Project", "Project")
                        .WithMany("Steps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("nirmata.Data.Entities.Projects.Project", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
